# Paths
path:
    raw_directory: ''
    processed_df_path: '/sensorsbp/processed_mimic3/ppgbp_dataset/ppgbp_data_bw_bsr_2s.pkl'
    split_df_path: '/sensorsbp/processed_mimic3/ppgbp_dataset/all_ppgbp_data_bw_bsr_2s_df.pkl'

# Preprocessing
param_process:
    is_align: true
    seg_length: 2
    fs: 125

param_bsr: # parameter of bad signal removal
    p2p_thrsh: 8

param_bw: # parameters of baseline wandering
    n_padding: 1

param_split:
    type: "cv" # "hoo" for UCI, "cv" for sensors
    fold: 5 # for "cv" method
    is_mix: false
    random_state: 0


