# Paths
path:
    raw_directory: ''
    processed_df_path: '/sensorsbp/processed_mimic3/uci_dataset/uci2_data_bw_bsr_5s.pkl' #uci_data_bw4_bsr_5s.pkl'
    demo_df_path:   # demographic data
    split_df_path: '/sensorsbp/processed_mimic3/uci_dataset/all_uci2_data_bw4_bsr_5s_df.pkl'

# Preprocessing
param_process:
    is_align: true
    seg_length: 5 
    fs: 125

param_bsr: # parameter of bad signal removal
    p2p_thrsh: 8

param_bw: # parameters of baseline wandering
    n_padding: 1

param_split:
    type: "hoo" # "hoo" for UCI, "cv" for sensors
    fold:  # for "cv" method
    is_mix: false
    random_state: 100
    tr_part: ['Part_1', 'Part_2'] # for UCI
    val_part: ['Part_3'] # for UCI
    ts_part: ['Part_4']  # for UCI



