# --------------------------------------------------------------------------------------------------
defaults:
  - override hydra/sweeper: optuna
  # - override hydra/sweeper/sampler: tpe
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

# --------------------------------------------------------------------------------------------------
hydra:
  sweeper:
    sampler:
      seed: 123
      _target_: optuna.samplers.TPESampler
      consider_prior: true
      prior_weight: 1.0
      consider_magic_clip: true
      consider_endpoints: false
      n_startup_trials: 10
      n_ei_candidates: 24
      multivariate: false
      warn_independent_sampling: true
    direction: minimize
    study_name: ${exp.exp_name}
    storage: null
    n_trials: 100
    n_jobs: 16

    search_space:
      param_model.n_estimators: 
        type: categorical
        choices: [10,50,100,200,300,400,500,800,1000]
      param_model.max_depth:
        type: int
        low: 1
        high: 100
      param_model.lr:
        type: float
        low: 0.0001
        high: 1
      param_model.leaves:
        type: int
        low: 3
        high: 50
      param_model.min_samples:
        type: int
        low: 3
        high: 100
      param_model.subsample:
        type: categorical
        choices: [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9]


# Paths
path:
    model_directory: "./model-${exp.model_type}"
    mlflow_dir: "./mlruns" # relative path to the project root

# --------------------------------------------------------------------------------------------------
# exp settings
exp:
    fs: 125
    N_fold: 5
    random_state: 123456
    model_type: "lgb" #"attnunet1d"
    data_name: sensors
    exp_name: ${exp.data_name}-${exp.model_type}-${param_loader.label}-tune
    subject_dict: ../../datasets/splitted/${exp.data_name}_dataset/feat_fold
    feat_importance: ../../feat_importance/${exp.data_name}_dataset/featImportance-SP.pkl
    loader: "feature"
    cv: cv

# --------------------------------------------------------------------------------------------------
# features & labels

# data laading / features
param_loader:
    phase_match: True
    filtered: True
    feat: [None] #["vpg"] 
    ppg_norm: "None" # glob_mm, glob_z, loc_z, loc_mm
    bp_norm: "None" # glob_mm, glob_z, loc_z, loc_mm
    label: "SP"
    rate_features: 1.0
    
# --------------------------------------------------------------------------------------------------
# trainer param
objective:
  type: "val_mae"
  mode: "min"
param_trainer:
    max_epochs: 1
    check_val_every_n_epoch: 1
    progress_bar_refresh_rate: 5
    gpus: "1"
    auto_lr_find: True
    auto_scale_batch_size: "binsearch"
param_early_stop:
    monitor: ${objective.type}
    min_delta: 0.00
    patience: 5
    verbose: True
    mode: ${objective.mode}


# --------------------------------------------------------------------------------------------------
#  model param
param_model:
    n_estimators: 400
    max_depth: 8
    lr: 0.01
    leaves: 31
    min_samples: 50
    subsample: 0.5
    colsample_bytree: 1.0
    n_workers: 10


# --------------------------------------------------------------------------------------------------
logger:
    param_ckpt:
        # dirpath: ${model_directory}
        monitor: ${objective.type}
        filename: "{epoch:02d}-{${objective.type}:.3f}"
        save_top_k: 1
        mode: ${objective.mode}
    log_lightning: False


