path:
  model_directory: ./model-${exp.model_type}
  mlflow_dir: ./mlruns
exp:
  fs: 125
  N_fold: 5
  random_state: 123456
  model_type: lgb
  data_name: bcg
  exp_name: ${exp.data_name}-${exp.model_type}-${param_loader.label}
  subject_dict: ../../datasets/splitted/${exp.data_name}_dataset/feat_fold
  feat_importance: ../../datasets/splitted/${exp.data_name}_dataset/featImportance-${param_loader.label}.pkl
  loader: feature
  cv: cv
param_loader:
  phase_match: true
  filtered: true
  feat:
  - None
  ppg_norm: None
  bp_norm: None
  label: SP
  rate_features: 0.05
objective:
  type: val_mae
  mode: min
param_trainer:
  max_epochs: 1
  check_val_every_n_epoch: 1
  progress_bar_refresh_rate: 5
  gpus: '1'
  auto_lr_find: true
  auto_scale_batch_size: binsearch
param_early_stop:
  monitor: ${objective.type}
  min_delta: 0.0
  patience: 5
  verbose: true
  mode: ${objective.mode}
param_model:
  rate_features: 0.05
  n_estimators: 150
  max_depth: 1
  lr: 0.01
  leaves: 31
  min_samples: 50
  subsample: 0.5
  colsample_bytree: 1.0
  n_workers: 10
logger:
  param_ckpt:
    monitor: ${objective.type}
    filename: '{epoch:02d}-{${objective.type}:.3f}'
    save_top_k: 1
    mode: ${objective.mode}
  log_lightning: false
