path:
  model_directory: ./model-${exp.model_type}
  mlflow_dir: ./mlruns
exp:
  fs: 125
  N_fold: 5
  random_state: 100
  data_name: ppgbp
  model_type: spectroresnet
  exp_name: ${exp.data_name}-${exp.model_type}
  subject_dict: ../../datasets/splitted/${exp.data_name}_dataset/signal_fold
  loader: waveform
  cv: cv
param_loader:
  ppg_norm: loc_z
  bp_norm: glob_mm
objective:
  type: val_mse
  mode: min
#param_test:
#  save_path: /sensorsbp/prediction/ppgbp_dataset/spectroresnet_ppgbp_nobw.pkl
param_trainer:
  max_epochs: 100
  check_val_every_n_epoch: 2
  progress_bar_refresh_rate: 5
  gpus: '0'
  auto_lr_find: true
  auto_scale_batch_size: binsearch
param_early_stop:
  monitor: ${objective.type}
  min_delta: 0.0
  patience: 10
  verbose: true
  mode: ${objective.mode}
param_model:
  N_epoch: 256
  batch_size: 32
  lr: 0.001
  in_channel: 1
  num_filters: 32
  num_res_blocks: 4
  cnn_per_res: 3
  kernel_sizes:
  - 8
  - 5
  - 3
  max_filters: 64
  pool_size: 3
  pool_stride_size: 2
  n_dft: 16
  n_hop: 16
  fmin: 0.0
  fmax: 25
  mlp_size: 144 
  mid_hidden: 64
  gru_hidden: 64
  UseDerivative: false
  model_verbose: false
logger:
  param_ckpt:
    monitor: ${objective.type}
    filename: '{epoch:02d}-{${objective.type}:.3f}'
    save_top_k: 1
    mode: ${objective.mode}
