
# Paths
path:
    data: "../../datasets/preprocessed/sensors.pkl" # Path to file with the segmented data
    save_name: "../../datasets/preprocessed/sensors_mabp.pkl" # File name to save the signal data

# frequency sampling rate of the signals
fs: 125

# PARAMS
limit_cycle: 149
added: 15
threshold: 1.25

# Parameters for parallelization
parallel:
    n_jobs: -1
    verbose: 0
  
# Parameters for splitting
splitting:
    # Paths
    path:
        processed_df_path: '../../datasets/preprocessed/sensors_mabp.pkl' # Path to file with the processed data (signal or features based dataset)
        split_df_path: '../../datasets/splitted/sensors_mabp.pkl' # File name to save the splitted data
        mat_path: '../../datasets/splitted/sensors_dataset/' # Path to directory to save mat files

    # Parameters for the data splitter
    param_split:
        type: "cv" # "hoo" for Hold-One-Set-Out (for UCI), "cv" for k-fold Cross-Validation (for the rest)
        fold: 5 # Number of folds for "cv" method.
        frac:  # fraction of the dataset reserved for test in "hoo" method.
        is_mix: false # If false, all samples of each subject is ensured to be in only one partition. (true is discouraged)
        random_state: 0
    
    
    



